### ISSUE TITLE
Data loader class issues while mapping

### ISSUE THREAD

**Issue by bilalbaloch1** [ahmedbesbes/character-based-cnn#4]
I am using my dataset having three labels 0,1,2. While loading the dataset in data_loader class it generates key error. I think the issue is of mapping please guide.

```
Traceback (most recent call last):
  File "train.py", line 415, in <module>
    run(args)
  File "train.py", line 219, in run
    texts, labels, number_of_classes, sample_weights = load_data(args)
  File "/content/character-based-cnn/src/data_loader.py", line 55, in load_data
    map(lambda l: {1: 0, 2: 0, 4: 1, 5: 1, 7: 2, 8: 2}[l], labels))
  File "/content/character-based-cnn/src/data_loader.py", line 55, in <lambda>
    map(lambda l: {1: 0, 2: 0, 4: 1, 5: 1, 7: 2, 8: 2}[l], labels))
KeyError: '1'
```

**Comment by tbass134** [comment]
add `--group_labels=0 ` as an argument when calling train.py.
also, this only support binary classification(0,1)
